# Generated by Django 5.2.6 on 2025-09-23 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0002_alter_user_details_conatct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_Id', models.IntegerField(unique=True)),
                ('Admin_Name', models.CharField(max_length=50, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=255)),
                ('Contact', models.IntegerField(max_length=10, unique=True)),
                ('Created_At', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Id', models.IntegerField(unique=True)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=50)),
                ('Published_Year', models.IntegerField()),
                ('ISBN', models.CharField(max_length=20)),
                ('Total_Copies', models.IntegerField()),
                ('Available_Copies', models.IntegerField()),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('Edition', models.IntegerField(blank=True, null=True)),
                ('Added_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Last_Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Transaction_Id', models.CharField(max_length=20)),
                ('Issued_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Due_Date', models.DateTimeField(blank=True, null=True)),
                ('Returned_Date', models.DateTimeField(blank=True, null=True)),
                ('Fines', models.IntegerField(default=0)),
                ('Fine_Paid', models.BooleanField(default=False)),
                ('Status', models.CharField(choices=[('Issued', 'issued'), ('Due', 'due'), ('Returned', 'returned')], max_length=10)),
                ('Book_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.books')),
                ('Roll_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user_details')),
            ],
        ),
    ]
