# Generated by Django 5.2.6 on 2025-09-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Contact',
            field=models.IntegerField(unique=True),
        ),
    ]
