# Generated by Django 5.2.6 on 2025-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_admin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Admin_Id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
