# Generated by Django 5.2.6 on 2025-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_alter_admin_admin_id_alter_admin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Edition',
            field=models.CharField(blank=True, null=True),
        ),
    ]
