# Generated by Django 5.2.6 on 2025-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_books_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='lms_images/'),
        ),
    ]
