# Generated by Django 5.2.6 on 2025-10-16 12:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_books_image_bookissue_bookrequest'),
        ('UserApp', '0007_alter_user_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 12, 57, 9, 78315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user_details'),
        ),
    ]
