# Generated by Django 5.2.6 on 2025-10-16 13:06

import AdminApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_bookissue_due_date_alter_bookrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='due_date',
            field=models.DateTimeField(default=AdminApp.models.default_due_date),
        ),
    ]
