# Generated by Django 5.2.6 on 2025-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_alter_bookissue_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
