# Generated by Django 5.2.6 on 2025-10-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_remove_bookrequest_id_bookrequest_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='id',
        ),
        migrations.AddField(
            model_name='bookissue',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
