# Generated by Django 5.2.6 on 2025-10-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_remove_bookissue_id_bookissue_sno'),
        ('UserApp', '0007_alter_user_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user_details'),
        ),
    ]
