# Generated by Django 5.2.6 on 2025-09-13 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Sno', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_number', models.CharField(max_length=20, unique=True)),
                ('Conatct', models.IntegerField(max_length=10)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=20)),
                ('Year_of_study', models.IntegerField(max_length=2)),
                ('Graduation_year', models.IntegerField(max_length=4)),
                ('Address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='UserApp.user')),
            ],
        ),
    ]
