# Generated by Django 5.2.6 on 2025-09-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Conatct',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Graduation_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Year_of_study',
            field=models.IntegerField(),
        ),
    ]
