# Generated by Django 5.2.6 on 2025-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_user_details_conatct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Conatct',
            new_name='Contacts',
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
