# Generated by Django 5.2.6 on 2025-09-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_conatct_user_details_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='Graduation_year',
            new_name='Graduation_Year',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='Year_of_study',
            new_name='Year_of_Study',
        ),
    ]
