# Generated by Django 5.2.6 on 2025-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_rename_contacts_user_details_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Course',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
