# Generated by Django 5.2.6 on 2025-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_user_details_address_alter_user_details_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
